training:
  L1: false
  batch_size: 5
  n_epochs: 1000000
  n_iters: 3000001
  snapshot_freq: 10000
  snapshot_sampling: true
  sample_freq: 10000
  val_freq: 1000
  log_freq: 100
  log_all_sigmas: false

sampling:
  batch_size: 10
  ckpt_id: 520000
  final_only: true
  fid: false
  ssim: true
  fvd: false
  denoise: true
  subsample: 100
  num_samples4fid: 10000
  num_samples4fvd: 10000
  inpainting: false
  interpolation: false
  n_interpolations: 15
  consistent: true
  step_lr: 0.0
  n_steps_each: 0
  train: false
  num_frames_pred: 20
  clip_before: true
  max_data_iter: 100000
  init_prev_t: -1.0 # if >0, we start next_frame at prev_frame starting with noise t=init_prev_t
  one_frame_at_a_time: false
  preds_per_test: 1

fast_fid:
  revise: true
  batch_size: 1000
  num_samples: 1000
  begin_ckpt: 5000
  freq: 5000
  end_ckpt: 300000
  pr_nn_k: 3
  verbose: false
  ensemble: false
  step_lr: 0.0
  n_steps_each: 0

test:
  begin_ckpt: 5000
  end_ckpt: 300000
  batch_size: 100

data:
  Weights: 255
  Weight: 1
  dataset_valid: tianchi
  dataset: MovingRadar_V3
  image_height: 128
  image_width: 128
  channels: 4
  outchannels: 1
  patch: 2
  logit_transform: false
  zero_mean_normalization_255: true
  zero_mean_normalization: false
  max_min_mean_normalization: false
  uniform_dequantization: false
  gaussian_dequantization: false
  random_flip: true
  rescaled: false
  num_workers: 10
  num_digits: 2
  step_length: 0.1
  num_frames: 5
  num_frames_cond: 5
  num_frames_future: 0
  prob_mask_cond: 0.0
  prob_mask_future: 0.0
  prob_mask_sync: false

model:
  depth: deeper
  version: DDPM
  gamma: false
  arch: unetmore
  type: v1
  time_conditional: true
  dropout: 0.0
  sigma_dist: linear
  sigma_begin: 0.02
  sigma_end: 0.0001
  num_classes: 1000
  ema: true
  ema_rate: 0.999
  spec_norm: false
  normalization: InstanceNorm++
  nonlinearity: swish
  ngf: 128
  ch_mult:
    - 1
    - 1
    - 2
    - 3
    - 4
  num_res_blocks: 2 # 8 for traditional
  attn_resolutions:
    - 8
    - 16
    - 32 # can use only 16 for traditional
  n_head_channels: 128 # -1 for traditional
  conditional: true
  noise_in_cond: false
  output_all_frames: false # could be useful especially for 3d models
  cond_emb: false
  spade: false
  spade_dim: 256

optim:
  weight_decay: 0.000
  optimizer: "RMSProp"
  lr: 0.000001
  warmup: 5000
  beta1: 0.9
  amsgrad: false
  eps: 1.0e-08
  grad_clip: 1.0


#CUDA_VISIBLE_DEVICES=5 python runner.py --config configs/tianchi.yml --exp radar_ch_4_size_128_num --config_mod sampling.subsample=100